{
  self,
  config,
  ...
}:
{
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  hardware.uinput.enable = true;
  users.groups = {
    "${self.myvars.username}" = { };
    docker = { };
    wireshark = { };
    # for android platform tools's udev rules
    adbusers = { };
    dialout = { };
    # for openocd (embedded system development)
    plugdev = { };
    # misc
    uinput = { };
  };

  users.users."${self.myvars.username}" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    inherit (self.myvars) initialHashedPassword;
    home = "/home/${self.myvars.username}";
    isNormalUser = true;
    extraGroups = [
      self.myvars.username
      "users"
      "networkmanager"
      "wheel"
      "wireshark"
      "adbusers"
      "libvirtd"
      "input"
      "uinput"
      "video"
    ];
  };

  # root's ssh key are mainly used for remote deployment
  users.users.root = {
    initialHashedPassword = config.users.users."${self.myvars.username}".initialHashedPassword;
    openssh.authorizedKeys.keys =
      config.users.users."${self.myvars.username}".openssh.authorizedKeys.keys;
  };
}
