{
  userfullname = "mochouaaaaa";
  useremail = "nn.mochou+github@gmail.com";
  # generated by `mkpasswd -m scrypt`
  # initialHashedPassword = "$7$GU..../....uzKeUvQ/ke2lkFZ37CHXO0$jhKrdZykymOs7CJ2GBRAWxApfBoElvrythRG6vTdYb1";
  # TODO:
  #   > sudo -k; time (sudo echo "Authenticated")
  # [sudo] password for mochou:
  # Authenticated
  # ( sudo echo "Authenticated"; )  2.74s user 0.96s system 62% cpu 5.946 total

  # mkpasswd -m yescrypt
  initialHashedPassword = "$y$j9T$FblQdc6JW7sQSTdMjh2kQ1$GqXMmWVt86ooa4xe8wvt9gNN20urtxyFJf4VCYqWmmB";
  # TODO:
  #   > sudo -k; time (sudo echo "Authenticated")
  # [sudo] password for mochou:
  # Authenticated
  # ( sudo echo "Authenticated"; )  0.02s user 0.03s system 2% cpu 1.845 total

  # dotfilePath = "$HOME/.config/dotfile";
  #                 ^
  #                 |
  #                 +-- This is the path to your dotfiles directory.
  dotfilePath = "dotfile";
}
