{
  userfullname = "mochouaaaaa";
  useremail = "nn.mochou+github@gmail.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$GU..../....uzKeUvQ/ke2lkFZ37CHXO0$jhKrdZykymOs7CJ2GBRAWxApfBoElvrythRG6vTdYb1";

  # dotfilePath = "$HOME/.config/dotfile";
  #                 ^
  #                 |
  #                 +-- This is the path to your dotfiles directory.
  dotfilePath = "dotfile";
}
