[pycharm]
src.manual = "2025.2.3"
fetch.url = "https://download.jetbrains.com/python/pycharm-professional-$ver.tar.gz"

[goland]
src.manual = "2025.2.3"
fetch.url = "https://download.jetbrains.com/go/goland-$ver.tar.gz"

[datagrip]
src.manual = "2025.2.4"
fetch.url = "https://download.jetbrains.com/datagrip/datagrip-$ver.tar.gz"

[clion]
src.manual = "2025.2.3"
fetch.url = "https://download.jetbrains.com/cpp/CLion-$ver.tar.gz"
