# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clion = {
    pname = "clion";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/cpp/CLion-2025.1.tar.gz";
      sha256 = "sha256-LR6NG4Y5wpBFFhVnvD/IzfvZyP5UnS2pLSXp2adcQI0=";
    };
  };
  datagrip = {
    pname = "datagrip";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/datagrip/datagrip-2025.1.tar.gz";
      sha256 = "sha256-1kuzACdPJQnd6aPHPrZvRdGBWL9GyeYdPfxgLej4O10=";
    };
  };
  goland = {
    pname = "goland";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/go/goland-2025.1.tar.gz";
      sha256 = "sha256-zCJhf5viM6E2RNZT8gy6KbBSlby1u3esliHuVEeuNJo=";
    };
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "bfac9c1d04fc0e2900ca8facbd538138f70604a1";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "bfac9c1d04fc0e2900ca8facbd538138f70604a1";
      fetchSubmodules = false;
      sha256 = "sha256-2NoWGyvz3fOa3JyOYdfUNvAmHz4X9jE8kQKWxLdLuD4=";
    };
    date = "2025-05-20";
  };
  pycharm = {
    pname = "pycharm";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/python/pycharm-professional-2025.1.tar.gz";
      sha256 = "sha256-EoKQfxNKcm4Xu3/oy3CI5AaqT7+dkQ3vA2M1cvOmL4w=";
    };
  };
  rime-lmdg = {
    pname = "rime-lmdg";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-bQY3UoR0X3VNgh4waDwJ19R1RxiVnYYSOAJmnkSHm0U=";
    };
  };
}
