# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clion = {
    pname = "clion";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/cpp/CLion-2025.1.tar.gz";
      sha256 = "sha256-LR6NG4Y5wpBFFhVnvD/IzfvZyP5UnS2pLSXp2adcQI0=";
    };
  };
  datagrip = {
    pname = "datagrip";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/datagrip/datagrip-2025.1.tar.gz";
      sha256 = "sha256-1kuzACdPJQnd6aPHPrZvRdGBWL9GyeYdPfxgLej4O10=";
    };
  };
  goland = {
    pname = "goland";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/go/goland-2025.1.tar.gz";
      sha256 = "sha256-zCJhf5viM6E2RNZT8gy6KbBSlby1u3esliHuVEeuNJo=";
    };
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "4463316f8efe8b6dcdad022a9d2b3f11b1bc83a7";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "4463316f8efe8b6dcdad022a9d2b3f11b1bc83a7";
      fetchSubmodules = false;
      sha256 = "sha256-qITt1Ovrx47zmxDvUpQ2M57UWCmVoJePDxTVr1Xl9o8=";
    };
    date = "2025-04-17";
  };
  pycharm = {
    pname = "pycharm";
    version = "2025.1";
    src = fetchurl {
      url = "https://download.jetbrains.com/python/pycharm-professional-2025.1.tar.gz";
      sha256 = "sha256-EoKQfxNKcm4Xu3/oy3CI5AaqT7+dkQ3vA2M1cvOmL4w=";
    };
  };
  rime-lmdg = {
    pname = "rime-lmdg";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-IPLstNXtKUcbqf8ao0g4ptVgSgub3fH4xk7xwpmNfuw=";
    };
  };
}
