{ lib, config, ... }:
let
  cfg = config.modules'.desktop.shell.noctalia;
in
{
  config = lib.mkIf (cfg.enable && cfg.settings.templates.neovim) {

    programs.nixvim = {
      extraConfigLuaPost = ''
        local function source_matugen()
        	-- Update this with the location of your output file
        	local matugen_path = os.getenv("HOME") .. "/.config/nvim/generated.lua" -- dofile doesn't expand $HOME or ~

        	local file, err = io.open(matugen_path, "r")
        	-- If the matugen file does not exist (yet or at all), we must initialize a color scheme ourselves

        	if err ~= nil then
        		-- Some placeholder theme, this will be overwritten once matugen kicks in
        		vim.cmd("CatppuccinCompile")
        		vim.cmd("colorscheme catppuccin")
        	else
        		dofile(matugen_path)
        		io.close(file)
        	end
        end

        source_matugen()

        -- Main entrypoint on matugen reloads
        local function auxiliary_function()
        	source_matugen()
        end

        -- Register an autocmd to listen for matugen updates
        vim.api.nvim_create_autocmd("Signal", {
        	pattern = "SIGUSR1",
        	callback = auxiliary_function,
        })

      '';
    };
    xdg.configFile = {
      "nvim/init.lua".force = true;
    };

    programs.noctalia-shell.user-templates = {
      templates = {
        neovim = {
          inputPath = "${config.xdg.configHome}/noctalia/colorschemes/template.lua";
          outputPath = "${config.xdg.configHome}/nvim/generated.lua";
          postHook = "pkill -SIGUSR1 nvim";
        };
      };
    };

    xdg.configFile = {
      "noctalia/colorschemes/template.lua".text = ''
        -- Auto-generated by Matugen

        local base16 = {
        	base00 = "{{colors.background.default.hex}}",
        	base01 = "{{colors.surface_container_lowest.default.hex}}",
        	base02 = "{{colors.surface_container_low.default.hex}}",
        	base03 = "{{colors.outline_variant.default.hex}}",
        	base04 = "{{colors.on_surface_variant.default.hex}}",
        	base05 = "{{colors.on_surface.default.hex}}",
        	base06 = "{{colors.inverse_on_surface.default.hex}}",
        	base07 = "{{colors.surface_bright.default.hex}}",

        	base08 = "{{colors.error.default.hex}}",
        	base09 = "{{colors.tertiary.default.hex}}",
        	base0A = "{{colors.secondary.default.hex}}",
        	base0B = "{{colors.primary.default.hex}}",
        	base0C = "{{colors.tertiary_container.default.hex}}",
        	base0D = "{{colors.primary_container.default.hex}}",
        	base0E = "{{colors.secondary_container.default.hex}}",
        	base0F = "{{colors.error_container.default.hex}}",
        }

        local function base16_to_cat_colors(b)
        	return {
        		base = b.base00,
        		mantle = b.base01,
        		crust = b.base02,

        		overlay0 = b.base03,
        		overlay1 = b.base04,
        		text = b.base05,
        		subtext1 = b.base06,
        		subtext0 = b.base07,

        		red = b.base08,
        		peach = b.base09,
        		yellow = b.base0A,
        		green = b.base0B,
        		teal = b.base0C,

        		blue = b.base0D,
        		mauve = b.base0E,
        		maroon = b.base0F,

        		-- 你可以自己选择下面这些要不要映射
        		-- sky = b.base0C,
        		-- sapphire = b.base0D,
        		-- lavender = b.base0E,
        		-- rosewater = b.base0A,
        		-- flamingo = b.base09,
        		-- pink = b.base0E,
        	}
        end

        local function set_hl_mutliple(groups, value)
        	for _, v in pairs(groups) do
        		vim.api.nvim_set_hl(0, v, value)
        	end
        end

        vim.api.nvim_create_autocmd("ColorScheme", {
        	callback = function()
        		vim.api.nvim_set_hl(0, "Visual", {
        			bg = "{{colors.primary_container.default.hex}}",
        			fg = "{{colors.background.default.hex}}",
        		})

        		set_hl_mutliple({ "TSComment", "Comment" }, {
        			fg = "{{colors.on_tertiary_container.default.hex}}",
        		})

        		set_hl_mutliple({ "TSMethod", "Method" }, {
        			fg = "{{colors.tertiary.default.hex}}",
        		})

        		vim.api.nvim_set_hl(0, "TSBuiltin", {
        			bg = "NONE",
        		})

        		set_hl_mutliple({ "TSFunction", "Function" }, {
        			fg = "{{colors.secondary.default.hex}}",
        		})

        		vim.api.nvim_set_hl(0, "Keyword", {
        			fg = "{{colors.inverse_primary.default.hex}}",
        		})

        		vim.api.nvim_set_hl(0, "MsgArea", {
        			bg = "{{colors.surface_container_lowest.default.hex}}",
        			fg = "{{colors.primary.default.hex}}",
        		})
        	end,
        })

        local color_overrides = {
        	all = base16_to_cat_colors(base16),
        }

        require("plugins.ui.theme.mode").setup(color_overrides)

        require("catppuccin").compile()
        vim.cmd("colorscheme catppuccin")
      '';
    };
  };
}
