{
  pkgs,
  lib,
  ...
}:
{
  config = {
    programs.ssh = {
      enable = true;

      enableDefaultConfig = false;

      matchBlocks."*" = {
        forwardAgent = false;
        addKeysToAgent = "no";
        compression = false;
        serverAliveInterval = 0;
        serverAliveCountMax = 3;
        hashKnownHosts = false;
        userKnownHostsFile = "~/.ssh/known_hosts";
        controlMaster = "no";
        controlPath = "~/.ssh/master-%r@%n:%p";
        controlPersist = "no";
      };

      # All my ssh private key are generated by `ssh-keygen -t ed25519 -a 256 -C "xxx@xxx"`
      # Config format:
      #   Host —  given the pattern used to match against the host name given on the command line.
      #   HostName — specify nickname or abbreviation for host
      #   IdentityFile — the location of your SSH key authentication file for the account.
      # Format in details:
      #   https://www.ssh.com/academy/ssh/config
      extraConfig = ''
        Host github.com
          AddKeysToAgent yes
          ${lib.optionalString pkgs.stdenv.isDarwin "UseKeychain yes"}
          IdentityFile ~/.ssh/github
      '';
    };
  };
}
