{lib}: let
  customConfig = rec {
    username = "mochou";
    userfullname = "mochouaaaaa";
    useremail = "nn.mochou+github@gmail.com";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$7$CU..../....eljcZ6wMdzMIITQt.XFsn1$wDJIAx4MGcgDInqjtURmobO4JcYG/g9Z3OJUoIjcXZ5";

    packages = {
      wezterm = false; # default use kitty
      ollama = true;
      neovim = true;
      neovide = true;
      google-chrome = true;
      firefox = true;
      vscode = true;
      qq = true;
      wechat = true;
      telegram = true;
      pot = true; # translate tool
      flameshot = true;
      obs = true;
      steam = false;
    };

    # dotfilePath = "$HOME/.config/dotfile";
    dotfilePath = "dotfile";

    wm = {
      wayland = true;
      x11 = false;
    };
  };
in
  customConfig
