{lib}: {
  username = "mochou";
  userfullname = "mochouaaaaa";
  useremail = "nn.mochou+github@gmail.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....eljcZ6wMdzMIITQt.XFsn1$wDJIAx4MGcgDInqjtURmobO4JcYG/g9Z3OJUoIjcXZ5";

  packages = {
    ollama = true;
    neovim = true;
    google-chrome = true;
    firefox = true;
    vscode = true;
    jetbrains = {
      enable = true;
      pycharm = true;
      clion = false;
      datagrip = true;
      goland = true;
    };
    qq = true;
    wechat = true;
    telegram = true;
    pot = true; # translate tool
    flameshot = true;
    obs = true;
    steam = false;
  };

  envs = {
    pyenv = true;
    goenv = true;
    luaenv = true;
    nodenv = true;
  };

  # dotfilePath = "$HOME/.config/dotfile";
  dotfilePath = ".config/dotfile";

  # hyprland, kde
  desktop = {
    hyprland = true;
    niri = true;
    component = {
      stylix = false;
      rofi = true;
      swaylock = true;
      swaync = true;
      waybar = true;
      wlogout = true;
    };
  };

  virtual = {
    docker = true;
    qemu = false;
    virtualbox = true;
    vmware = false;
  };

  disk = {
    enable = false;
    name = "sda";
    filesystem = "ext4";
  };

  networking = {
    defaultGateway = "192.168.1.1";
    nameservers = ["8.8.8.8" "8.8.4.4"];

    mingzi = {
      useDHCPv6 = true;
      useDHCP = true;
      ipv4.addresses = [
        {
          address = "192.168.1.100";
          netmask = "255.255.255.0";
        }
      ];
    };
  };
}
