{
  config,
  lib,
  pkgs,
  myvars,
  username,
  ...
}:
{
  # `programs.git` will generate the config file: ~/.config/git/config
  # to make git use this config file, `~/.gitconfig` should not exist!
  #
  #    https://git-scm.com/docs/git-config#Documentation/git-config.txt---global
  # home.activation.removeExistingGitconfig = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
  #   rm -f ${config.home.homeDirectory}/.gitconfig
  # '';

  home.packages = with pkgs; [ emojify ];

  programs = {
    gh = {
      enable = true;
    };

    git-cliff = {
      enable = true;
      settings = {
        changelog = {
          body = ''
            ## What's Changed

            {%- if version %} in {{ version }}{%- endif -%}
            {% for commit in commits %}
              {% if commit.remote.pr_title -%}
                {%- set commit_message = commit.remote.pr_title -%}
              {%- else -%}
                {%- set commit_message = commit.message -%}
              {%- endif -%}
              * {{ commit_message | split(pat="''\n") | first | trim }}''\
                {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
                {% if commit.remote.pr_number %} in ''\
                  [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) ''\
                {%- endif %}
            {%- endfor -%}

            {%- if github -%}
            {% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
              {% raw %}''\n{% endraw -%}
              ## New Contributors
            {%- endif %}''\
            {% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
              * @{{ contributor.username }} made their first contribution
                {%- if contributor.pr_number %} in ''\
                  [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) ''\
                {%- endif %}
            {%- endfor -%}
            {%- endif -%}

            {% if version %}
                {% if previous.version %}
                  **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
                {% endif %}
            {% else -%}
              {% raw %}''\n{% endraw %}
            {% endif %}

            {%- macro remote_url() -%}
              https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
            {%- endmacro -%}
          '';
          trim = true;
          footer = ''
            <!-- generated by git-cliff -->
          '';
          postprocessors = [ ];
        };
        git = {
          conventional_commits = true;
          filter_unconventional = true;
          commit_parsers = [
            {
              message = "^feat";
              group = "Features";
            }
            {
              message = "^fix";
              group = "Bug Fixes";
            }
            {
              message = "^docs";
              group = "Documentation";
            }
            {
              message = "^refactor";
              group = "Refactoring";
            }
            {
              message = "^style";
              group = "Style";
            }
            {
              message = "^test";
              group = "Tests";
            }
            {
              message = "^chore";
              group = "Miscellaneous";
            }
          ];
        };
      };
    };
    git = {
      enable = true;
      lfs.enable = true;

      ignores = [
        "# General"
        ".AppleDouble"
        ".LSOverride"

        "# Thumbnails"
        "._*"

        "# Files that might appear in the root of a volume"
        ".Trash-1000"
        ".DocumentRevisions-V100"
        ".fseventsd"
        ".Spotlight-V100"
        ".TemporaryItems"
        ".VolumeIcon.icns"
        ".com.apple.timemachine.donotpresent"

        "# Directories potentially created on remote AFP share"
        ".AppleDB"
        ".AppleDesktop"
        "Network Trash Folder"
        "Temporary Items"
        ".apdisk"

        "# Folder view configuration files"
        ".DS_Store"
        "Desktop.ini"

        "# Thumbnail cache files"
        "._*"
        "Thumbs.db"

        "# Files that might appear on external disks"
        ".Spotlight-V100"
        ".Trashes"

        "# Compiled Python files"
        "__pycache__/"
        "*.pyc"

        "# Compiled C++ files"
        "*.out"

        "# Application specific files"
        "venv/"
        "node_modules/"
        ".sass-cache"

        "# Temp File"
        "*.swp"
        "*.swa"
        "*.swo"

        "# github merge file"
        "*.orig"

        "#vscode"
        ".vscode/"

        ".idea"

        "# direnv"
        ".direnv/"
      ];

      settings = {

        user = {
          name = username;
          email = myvars.useremail;
        };

        init.defaultBranch = "main";
        trim.bases = "develop,master,main"; # for git-trim
        push.autoSetupRemote = true;
        pull.rebase = true;

        # core.excludesfile = "${config.home.homeDirectory}/.gitignore_global";
        pager.log = "emojify";

        # replace https with ssh
        url = {
          "ssh://git@github.com/${username}" = {
            insteadOf = "https://github.com/mochouaaaaa";
          };
        };
      };

    };

    # A syntax-highlighting pager in Rust(2019 ~ Now)
    delta = {
      enable = true;
      options = {
        diff-so-fancy = true;
        line-numbers = true;
        true-color = "always";
        # features => named groups of settings, used to keep related settings organized
        # features = "";
      };
    };

  };
}
